### PR TITLE
Correct the transition degrees on the composition polynomial (H)

### LINKED ISSUE #184: Correct the transition degrees on the composition polynomial (H)
Prover and verifier use the same wrong number. You have to take the degree after dividing by the zerofier, not before.

### PR DESCRIPTION
**Pull request by gabrielbosio**
## Description

Prover and verifier use the same wrong number. You have to take the degree after dividing by the zerofier, not before.
Resolves #184.
Ignores Fibonacci test with F17 until we have a mocked Transcript. With the current Transcript, we are having a polynomial from a FRI layer that is 0, so it has no coefficients and the test fails.

## Type of change

- [x] Bug fix

## Checklist
- [x] Linked to Github Issue

### CODE REVIEW

File: proving-system/stark/src/lib.rs [hunk 1]
```diff
@@ -100,6 +100,7 @@ mod tests {
         assert!(verify(&result, &fibonacci_air));
     }
 
+    #[ignore]
```
Comment (gabrielbosio) [inline proving-system/stark/src/lib.rs:103]: Ignores Fibonacci test with F17 until we have a mocked Transcript. With the current Transcript, we are having a polynomial from a FRI layer that is 0, so it has no coefficients and the test fails.

**Review by jrchatruc — APPROVED** [review]
